import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="cupcake">
      <meta
        name="fc:miniapp"
        content='{
          "version": "1",
          "imageUrl": "https://media.discordapp.net/attachments/535551463187808309/1392906503333216359/image.png?ex=68713cc5&is=686feb45&hm=9bc3d20d3ba70fa34d8904d92f8d0edf0417e90128447cb3a215d8f4ac573a5b&=&format=webp&quality=lossless&width=1640&height=1092",
          "button": {
            "title": "Launch FamFi",
            "action": {
              "type": "launch_miniapp",
              "name": "FamFi"
            }
          }
        }
        '
      />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
